GET http://localhost:8080/users/event_registrations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1AYS5jb20iLCJleHAiOjE3MjYyNDI0MzYsInVzZXJJZCI6MX0.8A5r1VrftJGsn3armd_A89lTBCfCA4K-nB2n4OV2Yns
