apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-hub-role-binding
  namespace: event-hub
subjects:
  - kind: ServiceAccount
    name: event-hub-service-account
    namespace: event-hub
roleRef:
  kind: ClusterRole
  name: event-hub-role
  apiGroup: rbac.authorization.k8s.io
