apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventhub-backend-role-binding
  namespace: eventhub
subjects:
  - kind: ServiceAccount
    name: eventhub-backend-service-account
    namespace: eventhub
roleRef:
  kind: ClusterRole
  name: eventhub-backend-role
  apiGroup: rbac.authorization.k8s.io
