apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-backend
  namespace: eventhub
  labels:
    app: eventhub-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhub-backend
  template:
    metadata:
      labels:
        app: eventhub-backend
    spec:
      containers:
        - name: eventhub-backend
          image: "docker.io/manvendraniranjan528/eventhub-backend:2.0.0-arm64"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080      
